### ISSUE TITLE
Bug in 2.9.8? 

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts#174] opened 2022-03-15 19:51 UTC
I'm not sure if its just me or the cause but this same chart which looked fine in 2.9.7, now in 2.9.8 the Legend (the word "Trend") is overlapping the xAxis values, see below, 2.9.7 is on the bottom. 
![IMG_4117](https://user-images.githubusercontent.com/9816100/158459845-8cbd26d9-f8ab-4ade-9a7a-b5d460527367.jpg)
![IMG_4118](https://user-images.githubusercontent.com/9816100/158459856-5ceb697f-4642-4573-a9d4-aed0e363c4f3.jpg)

**Comment by willdale** [comment] 2022-03-16 07:41
This should be fixed in v2.9.9.

Thanks

**Closed by willdale** 2022-03-16 07:41 UTC

**Comment by sai-manoj-kumar** [comment] 2022-03-23 05:20
@gesabo I am working on fixing this issue after including the reverted fix. I am not able to repro this issue with MutliLineChart. Can you please share the code you used to create this chart? In specific, I want to understand which chart type you are using.

**Comment by gesabo** [comment] 2022-03-25 14:49
@sai-manoj-kumar after checking my code I realized I was actually adding my own custom "legend" for the word Trend in the screenshot, so whatever changed in version 2.9.8 somehow made my Text view overlap the chart: 
```

     VStack(alignment: .leading, spacing: -20) {
                    
                    BarChart(chartData: unwrappedData)
                            .extraLine(chartData: unwrappedData, legendTitle: "") {
                                makeTrendData(data: athlyticDataStore.past60DaysOr6MonthsRecoveryScoreObjects?.suffix(60).compactMap { Double($0.recoveryScore)})
                            } style: {
                                showWeeklyAverageChart ? extraLineHiddenStyle : extraLineStyle
                            }
                        .touchOverlay(chartData: unwrappedData) //to be able to tab to see points need both .touchOverlay and .floatingInfoBox
                        .floatingInfoBox(chartData: unwrappedData)
                        .xAxisLabels(chartData: unwrappedData)
                        .yAxisLabels(chartData: unwrappedData)
                        .id(unwrappedData.id)
                        .animation(nil) //this prevents any of the chart from animating
                        .unredacted()
                    if !showWeeklyAverageChart {
                        if makeTrendData(data: athlyticDataStore.past60DaysOr6MonthsRecoveryScoreObjects?.suffix(60).compactMap { Double($0.recoveryScore)}).count > 1 {
                            
                            HStack {
                                RoundedRectangle(cornerRadius: 2.0)
                                    .foregroundColor( colorScheme == .dark ? Color(.label) : TrackerConstants.trendLineColor)
                                    .frame(width: 8.0, height: 8.0)
                                Text("Trend")
                                    .font(.footnote)
                                    .unredacted()
                            }
                        }
                 }
                 
             }
```

**Comment by sai-manoj-kumar** [comment] 2022-03-28 15:02
@gesabo, Thanks for sharing the code. I think it is happening because of the spacing of -20 in your VStack. I was able to repro the issue along with the PR. After removing the spacing: -20, the issue is gone. Please confirm if this works or not.

**Comment by gesabo** [comment] 2022-03-28 15:23
@sai-manoj-kumar thank you yes it seems like removing spacing of -20 solves the issue using version 2.9.8 and 2.9.9 as well.  👍

**Comment by sai-manoj-kumar** [comment] 2022-03-28 16:32
@gesabo Thanks for confirming it quickly. 

@willdale Can you please revert the reverted PR again? Thanks
