### ISSUE TITLE
BarChartStyle  xAxisLabelsFrom  dataPoints not showing? 

### ISSUE THREAD

**Issue by gesabo** [willdale/SwiftUICharts#78] opened 2021-05-20 19:59 UTC
I noticed in your demo project for a ranged bar chart, you hard code the xAxisLabels  `xAxisLabels: ["00:00", "12:00", "00:00"]` but I would like to load them dynamically from my data points as in `xAxisLabelsFrom    : .dataPoint(rotation: .degrees(0))` but they aren't showing up.  Am I doing something wrong or is this not possible yet? Here is a gist of my code, apologies for the cruft, work in progress...

https://gist.github.com/gesabo/9dc3758cd167544c953953e70a31b4b6

**Comment by willdale** [comment] 2021-05-23 09:09
Hi, This should be fixed now in v2.6.4. 

Let me know if its not.

Thanks,
Will

**Comment by gesabo** [comment] 2021-05-24 19:12
@willdale thanks working now!  One issue, is there any way to add some granularity to position of the XAxsisLabels?  See here, it looks like alignment is based on the first bar perhaps? 🤔  Or is there something I'm doing wrong here? 

![IMG_CC94BB22F96D-1](https://user-images.githubusercontent.com/9816100/119396132-78a90a00-bca2-11eb-98dc-4c50a3c7d8c1.jpeg)

**Comment by willdale** [comment] 2021-05-24 20:29
Hmmm, I can't replicate it. Can you send over some working, tidy code please?

**Comment by gesabo** [comment] 2021-05-24 20:38
@willdale I'm still using the code in my gist above, and this is the data I am plotting on a Ranged Bar Chart:  (these are sleep start and end times for 7 days using `TimeInterval` since midnight of each day. 

lowerValue = 33273.0 upperValue = 8673.0
lowerValue = 36843.0 upperValue = 10773.0
lowerValue = 29685.0 upperValue = 6195.0
lowerValue = 36990.0 upperValue = 7980.0
lowerValue = 39745.0 upperValue = 6895.0
lowerValue = 43474.0 upperValue = 11824.0
lowerValue = 35913.0 upperValue = 8583.0

**Comment by willdale** [comment] 2021-05-24 20:45
Can you send over minimal reproducible code that I can compile at this end without a rewrite. The gist doesn't have a `DataStore` object or a `SleepDay` object for example.

**Comment by gesabo** [comment] 2021-05-24 21:09
@willdale  sorry how about this https://gist.github.com/gesabo/50e6f28efce43a57e80e9fc285955276

**Comment by willdale** [comment] 2021-05-25 05:52
Hi @gesabo, no worries, thanks for sending it through. 

The issue seems to be that the lower and upper values are swapped around. So use:

```swift
RangedBarDataPoint(lowerValue:  8673.0,  upperValue: 33272.0,  xAxisLabel: "TUE"),
RangedBarDataPoint(lowerValue:  10773.0, upperValue: 36843.0, xAxisLabel: "WED"),
RangedBarDataPoint(lowerValue:  6195.0,  upperValue: 29685.0,  xAxisLabel: "THU"),
RangedBarDataPoint(lowerValue:  7980.0,  upperValue: 36990.0,  xAxisLabel: "FRI"),
RangedBarDataPoint(lowerValue:  6895.0,  upperValue: 39745.0,  xAxisLabel: "SAT"),
RangedBarDataPoint(lowerValue:  11824.0, upperValue: 43474.0, xAxisLabel: "SUN"),
RangedBarDataPoint(lowerValue:  8583.0,  upperValue: 35913.0,  xAxisLabel: "MON")
```

Hope this helps.

**Comment by willdale** [comment] 2021-05-25 17:36
Seeking clarification:

What would happen in your system if someone went to bed before midnight?

**Comment by gesabo** [comment] 2021-05-25 17:38
@willdale great question! I was just prototyping this with my data which is always after midnight but I was going to move the timeIntervalSince to since 6pm the day before 👍

**Comment by willdale** [comment] 2021-05-25 19:57
Does the follow solution work? 

```swift
let day = 860000.0
        
let rangeBarDataPoints = [
     RangedBarDataPoint(lowerValue: day - 33272.0, upperValue: day - 8673.0 , xAxisLabel: "TUE"),
     RangedBarDataPoint(lowerValue: day - 36843.0, upperValue: day - 10773.0, xAxisLabel: "WED"),
     RangedBarDataPoint(lowerValue: day - 29685.0, upperValue: day - 6195.0 , xAxisLabel: "THU"),
     RangedBarDataPoint(lowerValue: day - 36990.0, upperValue: day - 7980.0 , xAxisLabel: "FRI"),
     RangedBarDataPoint(lowerValue: day - 39745.0, upperValue: day - 6895.0 , xAxisLabel: "SAT"),
     RangedBarDataPoint(lowerValue: day - 43474.0, upperValue: day - 11824.0, xAxisLabel: "SUN"),
     RangedBarDataPoint(lowerValue: day - 35913.0, upperValue: day - 8583.0 , xAxisLabel: "MON"),
]
```

---

The order of highest and lowest is moderately structural to how chart type works. It is unlikely I will have time to look at flipping it any time soon, if you can put a pull request in, I'll more than gladly look at it.

**Comment by gesabo** [comment] 2021-05-25 20:25
@willdale that seems to work fairly well!  Thank you!

**Closed** 2021-05-29 06:15 UTC
Labels: bug
